FROM node:20

WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Подключаем код через volume для hot reload
# COPY . .  # не нужно для dev, используем volume

CMD ["npm", "run", "dev", "--", "--host"]
