from services import analytics_service

METRICS = {
    "employees-df": {"func": analytics_service.get_employees_df, "has_plot": False, "title": "All", },
    "average-experiance": {"func": analytics_service.get_average_experiance, "has_plot": False, "title": "Средний опыт сотрудников", },
    "average-fullyears": {"func": analytics_service.get_average_fullyears, "has_plot": False, "title": "Средний возраст сотрудников", },
    "count-by-sex": {"func": analytics_service.get_count_by_sex, "title": "Количество сотрудников по полу", },
    "employee-count-by-department": {"func": analytics_service.get_employee_count_by_department, "has_plot": False, "title": "Количество сотрудников по департаментам", },
    "count-by-department-level": {"func": analytics_service.get_count_by_department_level, "has_plot": True, "type_chart": 'bar', "title": "Количество сотрудников в департаменте", },
    "get-employees-by-region": {"func": analytics_service.get_employees_by_region, "has_plot": True, "type_chart": 'bar', "title": "Количество сотрудников по регионам",  "big": True,},
    "average-tenure-until-fire": {"func": analytics_service.get_average_tenure_until_fire, "has_plot": False, "title": "Средний срок работы до увольнения", },
    "average-experience-by-department": {"func": analytics_service.get_average_experience_by_department, "has_plot": True, "type_chart": 'bar', "title": "Средний опыт сотрудников в департаменте", },
    "average-fte-by-department": {"func": analytics_service.get_average_fte_by_department, "has_plot": True, "type_chart": 'bar', "title": "Средний FTE в департаменте", },
    "average-experience-by-region": {"func": analytics_service.get_average_experience_by_region, "has_plot": True, "type_chart": 'bar', "title": "Средний опыт работников по регионам", },
    "fired-count": {"func": analytics_service.get_fired_count, "has_plot": False, "title": "Общее количество увольнений", },
    "hire-count": {"func": analytics_service.get_hire_count, "has_plot": False, "title": "Общее количество найма", },
    "count-by-work-form": {"func": analytics_service.get_count_by_work_form, "has_plot": True, "type_chart": 'pie', "title": "Количество сотрудников по форме работы офис/удаленка", },
    "fte-sum": {"func": analytics_service.get_fte_sum, "has_plot": False, "title": "Сумма ставок FTE", },
    "fte-mean": {"func": analytics_service.get_fte_mean, "has_plot": False, "title": "Средний FTE", },
    "turnover-rate-by-month": {"func": analytics_service.get_turnover_rate_by_month, "has_plot": False, "type": 'bar', "title": "Текучесть кадров за выбранные месяцы", },
    "turnover-rate-by-department": {"func": analytics_service.get_turnover_rate_by_department, "has_plot": False, "title": "Текучесть в департаменте", },
    "hires-and-fires-share-by-department": {"func": analytics_service.get_hires_and_fires_share_by_department, "has_plot": True, "type_chart": 'doughnut', "title": "Доля новых наймов и увольнений в департаменте", },
    "turnover-rate-all-regions": {"func": analytics_service.get_turnover_rate_all_regions, "has_plot": True, "type_chart": 'bar', "title": "Текучесть по всем регионам", },
    "work-form-distribution": {"func": analytics_service.get_work_form_distribution, "has_plot": True, "type_chart": 'pie', "title": "Доля сотрудников по формам работы - офис/удаленка", },
    "average-fte-by-work-form": {"func": analytics_service.get_average_fte_by_work_form, "has_plot": True, "type_chart": 'pie', "title": "Средняя ставка FTE по формам работы - офис/удаленка", },
    "turnover-rate-by-age-category": {"func": analytics_service.get_turnover_rate_by_age_category, "has_plot": True, "type_chart": 'bar', "title": "Текучесть по возрастным категориям", },
    "turnover-rate-by-experience-category": {"func": analytics_service.get_turnover_rate_by_experience_category, "has_plot": True, "type_chart": 'bar', "title": "Текучесть по категориям опыта", },
    "average-experience-by-group": {"func": analytics_service.get_average_experience_by_group, "has_plot": False, "title": "Средний стаж по сервису или отделу", },
    "turnover-rate-by-service": {"func": analytics_service.get_turnover_rate_by_service, "has_plot": True, "type_chart": 'bar', "title": "Текучесть по сервисам", },
    "turnover-rate_by-work-form": {"func":  analytics_service.get_turnover_rate_by_work_form, "has_plot": True, "type_chart": 'pie', "title": "Текучесть по форме работы - офис/удаленка", },
    "fired-count-by-region": {"func": analytics_service.get_fired_count_by_region, "has_plot": True, "type_chart": 'bar', "title": "Количество увольнений по регионам", },
    "employee-count-by-service": {"func": analytics_service.get_employee_count_by_service, "has_plot": True, "type_chart": 'bar', "title": "Количество сотрудников по сервисам", },
    "average-fte-by-service": {"func": analytics_service.get_average_fte_by_service, "has_plot": True, "type_chart": 'bar', "title": "Средний FTE по сервисам", },
    "average-experience-by-region": {"func": analytics_service.get_average_experience_by_region, "has_plot": True, "type_chart": 'bar', "title": "Средний стаж по регионам", },
}
