from services import analytics_service

METRICS = {
    "get_employees_df": analytics_service.get_employees_df,
    "get_average_experiance": analytics_service.get_average_experiance,
    "get_average_fullyears": analytics_service.get_average_fullyears,
    "get_count_by_sex": analytics_service.get_count_by_sex,
    "get_employee_count_by_department": analytics_service.get_employee_count_by_department,
    "get_count_by_department_level": analytics_service.get_count_by_department_level,
    "get_get_employees_by_region": analytics_service.get_employees_by_region,
    "get_average_tenure_until_fire": analytics_service.get_average_tenure_until_fire,
    "get_average_experience_by_department": analytics_service.get_average_experience_by_department,
    "get_average_fte_by_department": analytics_service.get_average_fte_by_department,
    "get_average_experience_by_region": analytics_service.get_average_experience_by_region,
    "get_get_fired_count": analytics_service.get_fired_count,
    "get_get_hire_count": analytics_service.get_hire_count,
    "get_count_by_work_form": analytics_service.get_count_by_work_form,
    "get_fte_sum": analytics_service.get_fte_sum,
    "get_fte_mean": analytics_service.get_fte_mean,
    "get_turnover_rate_by_month": analytics_service.get_turnover_rate_by_month,
    "get_turnover_rate_by_department": analytics_service.get_turnover_rate_by_department,
    "get_hires_and_fires_share_by_department": analytics_service.get_hires_and_fires_share_by_department,
    "get_turnover_rate_all_regions": analytics_service.get_turnover_rate_all_regions,
    "get_work_form_distribution": analytics_service.get_work_form_distribution,
    "get_average_fte_by_work_form": analytics_service.get_average_fte_by_work_form,
    "get_turnover_rate_by_age_category": analytics_service.get_turnover_rate_by_age_category,
    "get_turnover_rate_by_experience_category": analytics_service.get_turnover_rate_by_experience_category,
    "get_average_experience_by_group": analytics_service.get_average_experience_by_group,
    "get_turnover_rate_by_service": analytics_service.get_turnover_rate_by_service,
    "get_turnover_rate_by_work_form": analytics_service.get_turnover_rate_by_work_form,
    "get_fired_count_by_region": analytics_service.get_fired_count_by_region,
    "get_employee_count_by_service": analytics_service.get_employee_count_by_service,
    "get_average_fte_by_service": analytics_service.get_average_fte_by_service,
    "get_average_experience_by_region": analytics_service.get_average_experience_by_region,
}
